site_name: WSL2を用いたdocker環境の構築手順
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Noto Sans JP
  extra:
    alternate:
      - name: English
        link: /en/
        lang: en
      - name: Japanese
        link: /
        lang: ja
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
      pygments_style: monokai
      linenums: true
  - pymdownx.superfences
repo_url: https://github.com/k-sugawara7201/docker-pages
repo_name: k-sugawara7201/docker-pages
plugins:
  search:
    lang: 'ja'
site_name: Docker Pages
copyright: "&copy; 2024 k-sugawara7201"